### ISSUE TITLE
Hello, I am a Korean developer

### ISSUE THREAD

**Issue by pdy1207** [marisabrantley/portfolio#1]
Your portfolio is so nice and pretty!
Could you please show me the code to smoothly navigate to that item when I click on something?
Even a simple example...

**Comment by marisabrantley** [comment]
Hi DoYoung!

Thank you so much!
The code is actually really simple. Add "scroll-behavior: smooth;" in the universal or HTML selector in CSS.

Example from my CSS/main.css code:
html {
  color: #222;
  font-size: 1rem;
  line-height: 1.4;
  scroll-behavior: smooth;
}

Hope that answers your question - if not, let me know. :smile:

**Comment by pdy1207** [comment]
Can you add code to "scroll-behavior: smooth;" in CSS and JS? The question is the code that goes to the corresponding item when the nav bar is clicked! As a novice developer, I'm sorry for the many questions.

**Comment by marisabrantley** [comment]
The above example was in CSS. It will do the trick. If have a specific issue you're dealing with, feel free to send a link to your code.

**Comment by pdy1207** [comment]
After testing it works fine thank you👍

**Comment by marisabrantley** [comment]
That's great! 😀
